#!/usr/bin/env sh
SERVERCOMM=localhost:7654
INSTALLPATH=/usr/bin
GAMENAME=led-memory-game

printf "(Rember to start the host cross-debug script too)\n\n"
gdbserver $SERVERCOMM $INSTALLPATH/$GAMENAME "$@"

